### ISSUE TITLE
WRITE PATCH CLOCK IN AND CLOCK OUT

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/TS-SQL-PATCH#3]
RL,

Write patch Clock in and clock out for SOPHIYA on 26/10/2015

**Comment by RAJALAKSHMIRAJKUMAR** [comment]
PATCH COMPLETED

GITHUB LINK : https://github.com/SSOMENSREPO/TS-SQL-PATCH/releases/tag/v3.5

status : **delivered**

**Comment by DHANDAPANISATTANATHAN** [comment]
# status: to_be_tested

**Comment by DHANDAPANISATTANATHAN** [comment]
# status: verified

Tested in TS INT nd verified

**Comment by DHANDAPANISATTANATHAN** [comment]
# status: Integrated

Int in TS PROD

**Comment by DHANDAPANISATTANATHAN** [comment]
# status: to_be_tested

Test in TS PROD

**Comment by DHANDAPANISATTANATHAN** [comment]
# status: verified

Verified in prod
