### ISSUE TITLE
Bala Chandar PROJECT PATCH

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/TS-SQL-PATCH#4]
@RAJALAKSHMIRAJKUMAR 

Write patch to update BC project. He worked 5 days In training.

Update all other ACE/PREMIUM project.

Close this today

**Comment by DHANDAPANISATTANATHAN** [comment]
# TASK OWNER:  @krishela 

Do this patch and close today!

**Comment by krishela** [comment]
Complete project name update patch for BC report and uploaded in below drive link

link:
https://drive.google.com/drive/folders/0Bwv4Rd7ZecjPTUloOXgwOVhOdFU

patch name:
SP_TS_UPDATE_EMPLOYEE_REPORT_PROJECT_VER_0.1_09112015

**Comment by DHANDAPANISATTANATHAN** [comment]
# status: Delivered

**Comment by DHANDAPANISATTANATHAN** [comment]
# status: to_be_tested

Test in UAT

**Comment by DHANDAPANISATTANATHAN** [comment]
# status: verified

Tested in UAT patch successfully updated BC reports

**Comment by DHANDAPANISATTANATHAN** [comment]
# status: Intergrated

Int in prod

**Comment by DHANDAPANISATTANATHAN** [comment]
# status: to_be_tested

Check in Prod

**Comment by DHANDAPANISATTANATHAN** [comment]
# status: verified

Checked in prod patch updated correctly

**Comment by DHANDAPANISATTANATHAN** [comment]
# status: Closed
